baseURL: "https://openprivacytech.org"
languageCode: en-us
title: Open Privacy Tech
theme: PaperMod


params:
  ShowReadingTime: true
  ShowFullTextinRSS: true
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  disableSpecial1stPost: true
  ShowPostNavLinks: true
  ShowShareButtons: false

menu:
  main:
    - identifier: resources
      name: Resources
      url: /resources/
      weight: 20
    - identifier: blog
      name: Blog
      url: /posts
      weight: 30
    - identifier: projects
      name: Projects
      url: /projects
      weight: 40

      