baseURL: "https://openprivacytech.org"
languageCode: en-us
title: Open Privacy Tech
theme: PaperMod


params:
  ShowReadingTime: true
  ShowFullTextinRSS: true
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  disableSpecial1stPost: true
  ShowPostNavLinks: false
  ShowShareButtons: true

menu:
  main:
    - identifier: resources
      name: Resources
      url: /resources/
      weight: 10
    - identifier: blog
      name: Blog
      url: /posts
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: community
      name: Community
      url: "https://communityinviter.com/apps/openprivacytech/openprivacytech"
      weight: 40
    - identifier: donate
      name: Donate
      url: "https://opencollective.com/openprivacytech"
      weight: 50

params:
  homeInfoParams:
    Title: Follow us
    Content: >
  socialIcons:
    - name: github
      url: "https://github.com/openprivacytech"
    - name: twitter
      url: "https://twitter.com/openprivacytech"      
    - name: linkedin
      url: "https://www.linkedin.com/company/openprivacytech"
    - name: slack
      url: "https://communityinviter.com/apps/openprivacytech/openprivacytech"  



